handle = load(fullfile(pwd,'\FlightLogs\2022-09-07\KC3\Parsed_LOG00002.mat'));
dataFrameKC.dataTable = handle.dataTable;


frameKC.accSample =  AccelerationSample("K4_VN200_Acceleration", dataFrameKC.dataTable.ACCELERATION, 800);
frameKC.rateSample =  AttitudeRateSample("K4_VN200_Rate", dataFrameKC.dataTable.ATTITUDE_RATE, 800);
frameKC.rateFilterredSample =  AttitudeRateSample("K4_VN200_Rate_Filterred", dataFrameKC.dataTable.FILTERED_ATTITUDE_RATE, 800);
frameKC.velSample =  VelocitySample("K4_VN200_Velocity", dataFrameKC.dataTable.VELOCITY_NED, 1);

trajSample = TrajectorySample("GPSPositionSample", dataFrameKC.dataTable.POSITION, ...
                              "VelNEDSample" , dataFrameKC.dataTable.VELOCITY_NED, ...
                              "AttitudeSample", dataFrameKC.dataTable.ATTITUDE, ...
                              "RateSample", dataFrameKC.dataTable.ATTITUDE_RATE,...
                              "FlightModeSample", dataFrameKC.dataTable.FCON_LOG_SP(:, ["Time", "FlightMode"]),...
                              "GPSSPSample", dataFrameKC.dataTable.FCON_SET_POSITION_SIG,...
                              "TerrainSPSample", dataFrameKC.dataTable.FCON_SET_TERRAIN_SIG, ...
                              "VelNEDSPSample", dataFrameKC.dataTable.FCON_LOG_SP(:, ["Time", "VelNorth", "VelEast", "VelDown"]), ...
                              "TrackingNEDSample", calcHomedirection, ...
                              "TargetInfoSample", dataFrameKC.dataTable.TARGET_INFO);


