@startuml
' Settings
' ============================

' use +,#,- instead of icons
'skinparam classAttributeIconSize 0

' horizontal distance in px
'skinparam nodesep 60 

' vertical distance in px
'skinparam ranksep 50

' use only straight lines (ortho/polyline)
 skinparam linetype ortho

' title
title TopicAnalyzerArchitecture

' Abstract Classes
' ============================

class Sample{
    -topic
    -fs
    +fft()
    +interpolate()
    +plot()
    #get_struct_info()
}

class AccelerationSample

class AttitudeSample

class AttitudeRateSample

class VelocitySample

class PositionSample

class CrossAnalyzer

class OFSSample{

}

class AnalyzerBase{
    -sampleList
    +automated()
}

class OFSAnalyzer {
    -OFSSample
    -LidarSample
    -AttitudeRateSample
    -AttitudeSample
    -VelocitySample
    +plot()
}

class FilterBase{
    
}


' Class hierachy
AttitudeRateSample -u-|> Sample
AttitudeSample -u-|> Sample
AccelerationSample -u-|> Sample
VelocitySample -u-|> Sample
PositionSample -u-|> Sample
LidarSample -u-|> Sample
OFSSample -u-|> Sample

'Sample -r-> FFTAnalyzer
AnalyzerBase -l-> Sample
LW20Sample -u-|> LidarSample

CrossAnalyzer -u-|> AnalyzerBase
OFSAnalyzer -u-|> AnalyzerBase

@enduml