@startuml

title Flight Analyzer Development

class TopicSample {
    + toTimeSeries()
}

class TSViewer {
    - TSArray: TimeSeries[n]
    - ColorTable: array[n][3]

    - Title: string 
    - AxisLabel: string
    - FigureFormat: varargin 
}

class TimeSeries {
    - Time: array 
    - Value: array 
    - Name: string 
    - Param: TSInfo

    + outlier()
    + fft(fs: int, [t1, t2])
}


interface TSInfo {
    # Unit: string 
    # AxisLabel: string 
}

interface AttitudeType {
    # Unit = "deg"
    # AxisLabel: "phi, theta, psi"
}


class FilterBase {
    + compute(ts: TimeSeries): TimeSeries
}

class Interpolator

class Smoothing {

}


TopicSample -r- "1..n" TimeSeries 


TimeSeries -r-> TSInfo
Interpolator -u-|> FilterBase
Smoothing -u-|> FilterBase

TSViewer --> "1..n" TimeSeries 

AttitudeType -u-|> TSInfo

@enduml